apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-deploy
  namespace: jenkins-project

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drone-deploy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: drone-deploy
    namespace: jenkins-project
